import os
import importlib.util

class Algorithm_manager():
    def __init__(self, path_manager):
        self.path_manager = path_manager
        self.sort_dir = self.path_manager.get_sort_dir()
        self.graph_dir = self.path_manager.get_graph_dir()
    def get_sort_algo_name(self):
        if not os.path.exists(self.sort_dir):
            return []
        results = []
        for file_name in os.listdir(self.sort_dir):
            full_path = os.path.join(self.sort_dir, file_name)
            if os.path.isfile(full_path) and file_name.endswith(".py"):
                results.append(os.path.splitext(file_name)[0])
        return results
    def get_graph_algo_name(self):
        if not os.path.exists(self.graph_dir):
            return []
        results = []
        for file_name in os.listdir(self.graph_dir):
            full_path = os.path.join(self.graph_dir, file_name)
            if os.path.isfile(full_path) and file_name.endswith(".py"):
                results.append(os.path.splitext(file_name)[0])
        return results
    def get_algo(self, type, algo_name):
        file_name = algo_name + ".py"
        if type == "sort":
            dir = self.sort_dir
        elif type == "graph":
            dir = self.graph_dir
        else:   
            return None
        
        full_path = os.path.join(dir, file_name)
        
        if not os.path.isfile(full_path):
            return None
        #the following lines are generated by chatgpt
        spec = importlib.util.spec_from_file_location(algo_name, full_path)
        if spec is None or spec.loader is None:
            return None

        module = importlib.util.module_from_spec(spec)
        spec.loader.exec_module(module)

        if hasattr(module, "output_algo"):
            return module.output_algo()

        return None